### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './darkflow/version.py'

### ISSUE THREAD

**Issue by ankitAMD** [ankitAMD/Darkflow-object-detection#2]
$ python setup.py build_ext --inplace
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    VERSION = imp.load_source('version', os.path.join('.', 'darkflow', 'version.py'))
  File "/home/ankitgupta/.conda/envs/abc/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "/home/ankitgupta/.conda/envs/abc/lib/python3.6/imp.py", line 158, in get_data
    return super().get_data(path)
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
![error3](https://user-images.githubusercontent.com/17083641/69795213-bfbf5780-11f1-11ea-819c-857d00524e94.png)

FileNotFoundError: [Errno 2] No such file or directory: './darkflow/version.py'

**Comment by ankitAMD** [comment]
file is missing so download correctly all fines ......go and check in /home/ankitgupta/Music/Darkflow-object-detection-master/darkflow and check version.py files are present or not.
